In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('pokemon_data.csv')
print(df.head(5))

#df_xlsx = pd.read_excel('pokemon_data.xlsx')
#print(df_xlsx.head(4))

df_txt = pd.read_csv('pokemon_data.txt', delimiter='\t')
print(df_txt.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [20]:
# Read headers
df_txt.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [21]:
## Read each column
#print(df['Name'][0:5])

print(df[['Name', 'HP', 'Attack']][0:5])

                    Name  HP  Attack
0              Bulbasaur  45      49
1                Ivysaur  60      62
2               Venusaur  80      82
3  VenusaurMega Venusaur  80     100
4             Charmander  39      52

In [22]:
## Read each row
print(df.iloc[1:4])

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False

In [23]:
## Read a specific location [R,C]

print(df.iloc[2,1])

Venusaur

In [25]:
## iterate rows
#for index,row in df.iterrows():
#    print(index, row['Name'])

#df.loc[df['Type 1'] == 'Fire']

#### Sorting/Describing Data

In [24]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [30]:
#df.sort_values('Name', ascending=False)

#df.sort_values(['Name', 'Type 1'])

#### Making changes to the data

In [25]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [40]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [54]:
df = df.drop(columns=['Total'])
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [103]:
df = pd.read_csv('pokemon_data.csv')

df['Total'] = df.iloc[:, 4:10].sum(axis=1) # Total column added to dataframe

cols = df.columns.tolist() # read a list from dataframe columns 
df = df[cols[0:4] + [cols[-1]] + cols[4:12]] # arranging dataframe columns as you required.

df.head(5)

# modified data can be written to csv
#df.to_csv('modified_pokemon_data.csv', index=False)
#df.to_excel('modified_pokemon_data.xlsx', index=False)
#df.to_csv('modified_pokemon_data.txt', index=False, sep='\t')

#### Filtering Data

In [117]:
df
#df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]
#df.loc[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison')]
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]

new_df
#new_df = new_df.reset_index()
new_df.reset_index(drop=True, inplace=True)
new_df
#new_df.to_csv('filtered.csv', index=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
1,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
2,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
3,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
4,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [4]:
#df.loc[df['Name'].str.contains('Mega')]
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,79,83,100,85,105,78,1,False
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
24,19,Rattata,Normal,NaN,30,56,35,25,35,72,1,False
25,20,Raticate,Normal,NaN,55,81,60,50,70,97,1,False
26,21,Spearow,Normal,Flying,40,60,30,31,31,70,1,False
27,22,Fearow,Normal,Flying,65,90,65,61,61,100,1,False
28,23,Ekans,Poison,NaN,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,60,85,69,65,79,80,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
31,26,Raichu,Electric,NaN,60,90,55,90,80,110,1,False
32,27,Sandshrew,Ground,NaN,50,75,85,20,30,40,1,False
33,28,Sandslash,Ground,NaN,75,100,110,45,55,65,1,False
34,29,Nidoran (Female),Poison,NaN,55,47,52,40,40,41,1,False
35,30,Nidorina,Poison,NaN,70,62,67,55,55,56,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
769,699,Aurorus,Rock,Ice,123,77,72,99,92,58,6,False
770,700,Sylveon,Fairy,NaN,95,65,65,110,130,60,6,False
771,701,Hawlucha,Fighting,Flying,78,92,75,74,63,118,6,False
772,702,Dedenne,Electric,Fairy,67,58,57,81,67,101,6,False
773,703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
774,704,Goomy,Dragon,NaN,45,50,35,55,75,40,6,False
775,705,Sliggoo,Dragon,NaN,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,90,100,70,110,150,80,6,False
777,707,Klefki,Steel,Fairy,57,80,91,80,87,75,6,False
778,708,Phantump,Ghost,Grass,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,85,100,122,58,75,54,6,False
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False
790,714,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [10]:
import re

#regular expressions
#df.loc[df['Type 1'].str.contains('Fire|Grass', regex=True)]

#df.loc[df['Type 1'].str.contains('fire|grass', flags = re.I, regex=True)]

# regular expression column name started with pi
df.loc[df['Name'].str.contains('^pi[a-z]*', flags = re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

#### Conditional Changes

In [17]:
#Changing the dataframe based upon some conditions

df = pd.read_csv('modified_pokemon_data.csv')
#print(df)

# Here I'm changing the 'Generation' and 'Legendary' column value to 'TEST VALUE', if Total column value is > 500
#df.loc[df['Total'] > 500, ['Generation', 'Legendary']] = 'TEST VALUE'
#df

# if Total column > 500, change Generation and Legendary column values
df.loc[df['Total'] > 500, ['Generation', 'Legendary']] = ['Test1', 'Test2']
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test1,Test2
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test1,Test2
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,Test1,Test2
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,Test1,Test2
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,Test1,Test2
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,Test1,Test2
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,Test1,Test2
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,Test1,Test2
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,700,Sylveon,Fairy,NaN,525,95,65,65,110,130,60,Test1,Test2
771,701,Hawlucha,Fighting,Flying,500,78,92,75,74,63,118,6,False
772,702,Dedenne,Electric,Fairy,431,67,58,57,81,67,101,6,False
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False
774,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False
775,705,Sliggoo,Dragon,NaN,452,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,Test1,Test2
777,707,Klefki,Steel,Fairy,470,57,80,91,80,87,75,6,False
778,708,Phantump,Ghost,Grass,309,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,474,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,335,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,335,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,Test1,Test2
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,Test1,Test2
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,Test1,Test2
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,Test1,Test2
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,Test1,Test2
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test1,Test2
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test1,Test2
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test1,Test2
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test1,Test2
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,Test1,Test2

#### Aggregate Statistics Group By